# Generated by Django 2.0 on 2018-01-08 22:00

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=32, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=32)),
                ('address_range_start', models.CharField(max_length=16)),
                ('address_range_end', models.CharField(max_length=16)),
                ('dis_time', models.DateTimeField()),
                ('create_time', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=32, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=16)),
                ('port', models.IntegerField()),
                ('check_time', models.DateTimeField()),
                ('save_time', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
