# Generated by Django 2.0 on 2017-12-12 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=32)),
                ('address_range_start', models.CharField(max_length=16)),
                ('address_range_end', models.CharField(max_length=16)),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=16)),
                ('port', models.IntegerField()),
                ('check_time', models.DateTimeField()),
                ('css', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.Pool')),
            ],
        ),
    ]
