# Generated by Django 2.0 on 2018-01-08 22:27

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=32)),
                ('address_range_start', models.CharField(max_length=16)),
                ('address_range_end', models.CharField(max_length=16)),
                ('dis_time', models.DateTimeField()),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=16)),
                ('port', models.IntegerField()),
                ('check_time', models.DateTimeField()),
                ('save_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
