# Generated by Django 2.0 on 2018-03-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0002_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Notification',
        ),
    ]
