# Generated by Django 2.0 on 2017-12-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0002_remove_response_pool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pool',
            old_name='end_time',
            new_name='dis_time',
        ),
    ]
