# Generated by Django 2.0 on 2017-12-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0003_auto_20171217_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='time',
            field=models.DateTimeField(default='2017-12-29 21:20:18'),
            preserve_default=False,
        ),
    ]
